// Mocks generated by Mockito 5.4.4 from annotations
// in fadhli_test_flutter/test/movie/movie_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fadhli_test_flutter/features/movie/data/datasources/movie_remote_datasource.dart'
    as _i3;
import 'package:fadhli_test_flutter/features/movie/data/models/movie_detail_model.dart'
    as _i2;
import 'package:fadhli_test_flutter/features/movie/data/models/movie_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieDetailModel_0 extends _i1.SmartFake
    implements _i2.MovieDetailModel {
  _FakeMovieDetailModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseMovieRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseMovieRemoteDatasource extends _i1.Mock
    implements _i3.BaseMovieRemoteDatasource {
  @override
  _i4.Future<List<_i5.MovieModel>> getMovieNowPlaying(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieNowPlaying,
          [page],
        ),
        returnValue: _i4.Future<List<_i5.MovieModel>>.value(<_i5.MovieModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.MovieModel>>.value(<_i5.MovieModel>[]),
      ) as _i4.Future<List<_i5.MovieModel>>);

  @override
  _i4.Future<List<_i5.MovieModel>> getMovieUpcaming(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieUpcaming,
          [page],
        ),
        returnValue: _i4.Future<List<_i5.MovieModel>>.value(<_i5.MovieModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.MovieModel>>.value(<_i5.MovieModel>[]),
      ) as _i4.Future<List<_i5.MovieModel>>);

  @override
  _i4.Future<_i2.MovieDetailModel> getMovieDetail(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [movieId],
        ),
        returnValue:
            _i4.Future<_i2.MovieDetailModel>.value(_FakeMovieDetailModel_0(
          this,
          Invocation.method(
            #getMovieDetail,
            [movieId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MovieDetailModel>.value(_FakeMovieDetailModel_0(
          this,
          Invocation.method(
            #getMovieDetail,
            [movieId],
          ),
        )),
      ) as _i4.Future<_i2.MovieDetailModel>);
}
